### ISSUE TITLE
ios8.3 系统报错 can't find variable performance 

### ISSUE THREAD

**Issue by ch1ch** [yyued/SVGAPlayer-Web#10]
在ios8.3的safari 和微信中无法显示运行。
safari会报错 can't find variable performance 。
请问如何解决，多谢-

**Comment by PonyCui** [comment]
没有遇到你说的问题

**Comment by ch1ch** [comment]
解决了，在之前加一段

 window.performance = window.performance || {} ;
 window.performance.now = window.performance.now ||( function()  {
   var st =Date.now();
    return function() { return Date.now() - st ;} 
} )() ;

就可以了。

**Comment by PonyCui** [comment]
这个 performance 的 polypill 在 Player 内部也是有实现的
