### ISSUE TITLE
SVGA.layabox undefined

### ISSUE THREAD

**Issue by solody** [yyued/SVGAPlayer-Web#11]
layabox版本 v1.7.12

试错步骤
1、 https://github.com/yyued/SVGAPlayer-Web/tree/master/patch/layabox/laya.webgl.js  Replace to {LayaProjectDir}/bin/libs/laya.webgl.js
2、add <script src="svga.layabox.min.js"></script> after layabox libs
3、run code:
```
var displayObject = new SVGA.layabox.Player('res/svga/rose_2.0.0.svga')
displayObject.setFrame(0, 0, 750, 750);
Laya.stage.addChild(displayObject)
```

Anythings wrong here? OR SVGA只支持特定版本的layabox？

**Comment by PonyCui** [comment]
你先看看 svga.layabox.min.js 路径是否正常，脚本是否成功加载。

**Comment by solody** [comment]
发现SVGA.layabox的确是没有定义，但SVGA.Player有定义，于是改了一下代码
```
new SVGA.Player('xxx.svga')
```
就可以了，是为什么呢，layabox属性废止了吗？

**Comment by PonyCui** [comment]
在更改为 UMD 后，layabox 似乎被覆盖了。

**Comment by PonyCui** [comment]
Fix on master.
Change Player to SVGA.LayaboxPlayer
