### ISSUE TITLE
problem of installation for layabox

### ISSUE THREAD

**Issue by solody** [yyued/SVGAPlayer-Web#12]
1. Patch laya.webgl.js library
Goto https://github.com/yyued/SVGAPlayer-Web/tree/master/patch/layabox Download laya.webgl.js
Replace to {LayaProjectDir}/bin/libs/laya.webgl.js
2. Prebuild JS
Goto https://github.com/yyued/SVGAPlayer-Web/tree/master/build Download svga.layabox.min.js
Add <script src="svga.layabox.min.js"></script> to index.html

这是两种安装方法，还是两个安装步骤？
我从上下文理解为步骤，因为第3个是可选的。

但是，出现了错误
```
TypeError: this.startCreate is not a function
```

然而如果我省略第1步，只做第二步，则运行正常，但仍然有另一个已知问题：[issues11: SVGA.layabox undefined](https://github.com/yyued/SVGAPlayer-Web/issues/11)

**Comment by solody** [comment]
为什么要替换layabox的webgl库？如果layabox升级版本，会不会有冲突

**Comment by PonyCui** [comment]
Patch 和 Prebuild JS 都需要执行

**Comment by PonyCui** [comment]
Patch 是因为 laya.webgl.js 缺少 Bezier 方法

**Comment by solody** [comment]
我patch了之后，出现 `TypeError: this.startCreate is not a function`

**Comment by PonyCui** [comment]
版本不兼容导致，你可以自行根据 diff 修改。

**Comment by solody** [comment]
要怎么改？不太会改啊，能指示一下吗？

**Comment by PonyCui** [comment]
fix on master.
