### ISSUE TITLE
ImageKey 是指什么？

### ISSUE THREAD

**Issue by hanyiTim** [yyued/SVGAPlayer-Web#13]
player.setImage('http://yourserver.com/xxx.png', 'ImageKey');   请问这里的imagekey 是只 动画的帧数？有demo吗

**Comment by PonyCui** [comment]
参照 Demo 中的代码。

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Web/blob/master/tests/canvas.html
imageKey 是设计师提供的，一般是素材的文件名。
