### ISSUE TITLE
报的这种错是什么原因呢？

### ISSUE THREAD

**Issue by Fzz0826** [yyued/SVGAPlayer-Web#19]
在谷歌中报的错误
1、Failed to load file:///C:/Users/fzz/Desktop/lx/img/aa.svga: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
2、InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').

在uc中报的错误
1、XMLHttpRequest cannot load file:///C:/Users/fzz/Desktop/lx/img/aa.svga. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, 

2、InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').

在火狐中预览是好的没有报错

**Comment by PonyCui** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS

**Comment by Fzz0826** [comment]
我是在本地引入的图片啊，也会有跨域？？？

**Comment by PonyCui** [comment]
你想想，没有跨域，你的本地文件还安全吗？

**Comment by Fzz0826** [comment]
我就是引入的本地的图片也会跨域吗？？？
图片路径就是这样的啊  
parser.load("./img/aa.svga", function (videoItem) {
                         player.setVideoItem(videoItem);
                        player.startAnimation();
            
            // player.startAnimationWithRange({location: 20, length: 1}, false); 
        }, function(error) {
            console.log(error.message);
        })

**Comment by Fzz0826** [comment]
我看了你这个demo  SVGAPlayer-Web-master
里面的图片引入路径是我一样的啊，parser.load("./samples/aa.svga", function (videoItem)
为什么你这个没有报错，我的就报错了呢？
是因为起不起服务的问题吗？

**Comment by hanyiTim** [comment]
告诉你个办法  把svga 转成base64  可以解决掉你这个问题，至于为啥跨域，看一下player.load的代码

**Comment by Fzz0826** [comment]
这个怎么转？？？

**Comment by PonyCui** [comment]
@Fzz0826 自行 Google 解决问题
