### ISSUE TITLE
drawOnCanvas.html 报错：Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by F3n67u** [yyued/SVGAPlayer-Web#2]
`npm start` 后打开 `http://127.0.0.1:8080/tests/drawOnCanvas.html` 页面报错：
```
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at Player._init (player.js:20)
    at Player (player.js:15)
    at new Player (svga.min.js:11699)
    at drawOnCanvas.html:12
```
看了下具体的原因是 `var player = new SVGA.Player()` 中没有指定 `container`，所以导致 `player.js` 中的 `this._container` 为 `undefined`

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Web/commit/d12087b2d829dccea92d5d0c3ad2324e5bf80b69
Fixed. Thank you!
