### ISSUE TITLE
onfinished回调问题

### ISSUE THREAD

**Issue by Blubiubiu** [yyued/SVGAPlayer-Web#23]
动画在开始前就触发了onfinished回调

**Comment by Blubiubiu** [comment]
网络请求的图片是否限制了100KB以内的禁止转base64，在哪里解除限制

**Comment by errnull** [comment]
你好，刚刚检查了一下代码，没有发现 onfinished  提前回调的问题，
麻烦把 Demo 发送到 help@svga.io，
这边会尽快回复你的。

网络请求没有什么限制哦。

**Comment by errnull** [comment]
你可以发个 Demo 给我看一下吗？
谢谢啦。

**Comment by errnull** [comment]
问题已解决。
