### ISSUE TITLE
版本优化

### ISSUE THREAD

**Issue by lijialiang** [yyued/SVGAPlayer-Web#26]
#### ➜ 现存在问题

* 开发构建工作流功能未完善
   * 开发 source map 是必须的，无需打包进去 build code
   * 浏览器自动自动刷新
* 模块问题
   * 过量 Class 类封装，性能损耗，部分转为 function exec
* 规范问题
   * [团队 JavaScript 规范](https://github.com/duowan/fe-guide/blob/master/javascript-guide.md)
  
#### ➜ 建议优化后模块分块

![image](https://user-images.githubusercontent.com/12247242/37381881-aaefa7b4-277a-11e8-9b97-6257e0d65ecd.png)

为了扩展以后渲染引擎的扩展，唯一 entry 文件，根据动态  alias 打包 Player Render Engine 的模块引入。无需每次支持其他渲染引擎创建新的 entry。

#### ➜ 其他优化

* Source Code 异步处理
* Promise 标准化，扩展支持 async / await 
* React / Vue.js 组件化
* 不同 Player Engine 兼容同一套接口写法

**Comment by reyhappen** [comment]
建议把flash播放器拆开成两个，一个专门用于IE6-8播放的A，一个专门用于加载文件和解析文件的B，IE9就只用这个B来加载和解析，而用canvas来播放，这样可以在IE9减少一个播放器的加载。另外flash播放的时候无法控制时间穿透，有时候我们需要在动画下层绑定事件，而canvas可以设置css样式pointer-events: none来屏蔽canvas事件，避免遮挡下层元素的事件响应。

**Comment by reyhappen** [comment]
建议把flash播放器拆开成两个，一个专门用于IE6-8播放的A，一个专门用于加载文件和解析文件的B，IE9就只用这个B来加载和解析，而用canvas来播放，这样可以在IE9减少一个播放器的加载。另外flash播放的时候无法控制时间穿透，有时候我们需要在动画下层绑定事件，而canvas可以设置css样式pointer-events: none来屏蔽canvas事件，避免遮挡下层元素的事件响应。 @lilijialiang @errnull

**Comment by lijialiang** [comment]
已分拆出 [lite](https://github.com/svga/SVGAPlayer-Web-Lite) 版本
