### ISSUE TITLE
ImageKey是什么东东啊？我们的设计师也不知道啊

### ISSUE THREAD

**Issue by ripeBoy** [yyued/SVGAPlayer-Web#27]
大佬，ImageKey是什么东东啊？我们的设计师也不知道啊，麻烦指点一下

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Web/issues/16
提问前先看看 Issue 列表好不好

**Comment by ripeBoy** [comment]
那请问一下哪里可以讨论交流呢，QQ群不让加，Issues不让提，要么你就别开源，要开源还是这种态度，有问题可以一起讨论，一起解决啊，为什么要这样呢，不要破坏技术圈，OK？

**Comment by ripeBoy** [comment]
删帖跑路，OK？

**Comment by PonyCui** [comment]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

------

我们只是开源，并没有任何义务回答你的问题。
