### ISSUE TITLE
功能建议：替换的图片和原图片尺寸不一致并且setImage未传transform参数时，默认缩放

### ISSUE THREAD

**Issue by F3n67u** [yyued/SVGAPlayer-Web#3]
在试用 svga 时，发现如果 setImage 替换的图片和原图片尺寸不一致，没有默认对替换的图片进行 transfrom 变换，这个在替换头像的场景是很不方便的，需要每次都计算出需要transform。相比较 web 端， android 和 ios 的 API 都提供了默认的 transform 变换的功能。

**Comment by PonyCui** [comment]
Feature added at https://github.com/yyued/SVGAPlayer-Web/tree/2.0.6
