### ISSUE TITLE
循环播放次数

### ISSUE THREAD

**Issue by jpdan** [yyued/SVGAPlayer-Web#31]
![tim 20180515092503](https://user-images.githubusercontent.com/3361732/40031348-e414e734-5821-11e8-8214-331c3cfd30bf.png)
循环播放大于1，永远只播放1次？

**Comment by errnull** [comment]
谢谢反馈， commit `57be372 `  中已修复

**Comment by ericeyang** [comment]
`<div src="rose_2.0.0.svga" loops="1" clearsAfterStop="true" style="styles..."></div>`

设置 loops = 1，会无限循环；

**Comment by Suzukaze-Yoru** [comment]
貌似还是有bug，设为 大于1的整数，并不会循环。在源码中也没看到有使用loops的地方。只是修复了那条语句？

**Comment by PonyCui** [comment]
你尝试一下最新 commit 上的 js

**Comment by Suzukaze-Yoru** [comment]
ok 拉去仓库最新的代码已解决
