### ISSUE TITLE
在react里获取失败是什么原因

### ISSUE THREAD

**Issue by yiwuxing** [yyued/SVGAPlayer-Web#36]
在react里使用的时候，通过npm安装，按照步骤使用。但是获取到的parse是空对象是什么原因？
var parser = new SVGA.Parser('#demoCanvas');这句错误了，打印出来的获取到的parser是空对象，
var player = new SVGA.Player('#demoCanvas')这个可以正常获取得到，请问是什么原因？

**Comment by PonyCui** [comment]
Provide a sample please.

**Comment by yiwuxing** [comment]
上传不了图片，我直接贴代码了

import React from 'react';
require('svgaplayerweb')

import styles from './Index.css';
import {Input, Icon, Spin, Button, Tabs, Modal, message, Affix, notification} from 'antd';
import 'antd/dist/antd.css'
const Search = Input.Search;
import hashiqiDog from '../../svgFile/hashiqiDog.svga'
import pageRight from '../../assets/pageRight.png'
const TabPane = Tabs.TabPane;
import '../../../node_modules/video-react/dist/video-react.css'
const imgVideoPicUrl = "https://image.huanqiushuju.com/"
class Index extends React.Component{
  constructor(props){
    super(props)
    this.state={videoUrl:"",renderState:true}
  }
  componentWillMount(){}
  componentDidUpdate() {
    let element = document.getElementById('demoCanvas')
    console.log("element", "#" +element.id)
    var player = new SVGA.Player('#' + element.id);
    var parser = new SVGA.Parser('#' + element.id); // 如果你需要支持 IE6+，那么必须把同样的选择器传给 Parser。
    console.log("player",player)
    console.log("parser",parser)
    parser.load('../../svgFile/hashiqiDog.svga', function(videoItem) {
      player.setVideoItem(videoItem);
      player.startAnimation();
    })
  }
  render(){
    console.log("-----props--rendeer",this.props)
    if(this.state.renderState){
      this.setState({renderState:false})
    }

     return (
      <div  style={{height:300,width:300,background:'black'}}  src="../../svgFile/hashiqiDog.svga" id="demoCanvas" className={styles.allContent}>

      </div>
       // <div style={{height:300,width:300,background:'black'}} src="../../svgFile/hashiqiDog.svga" id="demoCanvas" className={styles.allContent}>
       //
       // </div>
    )
  }
}

export default Index;

----------------------------------------------------------------------------
以下是打印出来的信息

<img width="1184" alt="svgconsole" src="https://user-images.githubusercontent.com/26779894/47141675-ca6fa380-d2f3-11e8-87c7-3ffc760a38d3.png">

**Comment by yiwuxing** [comment]
![reactsvg](https://user-images.githubusercontent.com/26779894/47141739-ed01bc80-d2f3-11e8-9ccb-29539f75c101.png)
这是刚才那个贴代码的那张图

**Comment by PonyCui** [comment]
Provides a zip package.

**Comment by yiwuxing** [comment]
文件太大，这里传太慢了，能有微信或者QQ嘛？

**Comment by PonyCui** [comment]
Just provide a tiny project reproduce issue.

**Comment by yiwuxing** [comment]
Waite a moment

**Comment by yiwuxing** [comment]
[testSvgPlayer.zip](https://github.com/yyued/SVGAPlayer-Web/files/2491074/testSvgPlayer.zip)
1.npm install
2.npm start
目标文件在src/components/Video/Index.js

**Comment by yiwuxing** [comment]
请问有回复吗？项目挺紧的？辛苦您了

**Comment by lilijialiang** [comment]
@yiwuxing 

```
Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.
```

**Comment by lilijialiang** [comment]
@yiwuxing

我大概看了一下你代码，有以下问题：

1. `parser.load(x.svga)`  x.svga 应该是一个静态文件路径，但是你的引入方式是相对路径，

**Comment by yiwuxing** [comment]
好的，谢谢
