### ISSUE TITLE
引入gif文件整个页面都在抖动

### ISSUE THREAD

**Issue by yiwuxing** [yyued/SVGAPlayer-Web#37]
本来开发没什么问题。svga文件能正常显示，引进gif动画图片后，前几次能正常显示，后面有车次不知道为什吗报了错，说svga.min.js。里的length出错了，好像是，然后再渲染就是页面一直抖动了，重启项目，重启电脑也没用，请问是什么原因呢？不能使用gif文件吗？

**Comment by PonyCui** [comment]
不支持 gif
