### ISSUE TITLE
用react的时候只是import进文件就已经报错是什么原因

### ISSUE THREAD

**Issue by yiwuxing** [yyued/SVGAPlayer-Web#38]
文件放在public 文件夹，在component的index.js文件里
import hashiqiDogSvga from '../../../public/hashiqiDogSvga.svga'
这样就已经报错，请问是什么原因

![svgaconsole11111](https://user-images.githubusercontent.com/26779894/48246954-63459a80-e42c-11e8-848c-2031522e56b4.png)

**Comment by yiwuxing** [comment]
已经npm install svgaPlayerWeb，在script里也已经引用了

**Comment by PonyCui** [comment]
svga 文件是不可以 import 的

**Comment by yiwuxing** [comment]
如果不import，只是引用的话，webpack就不会打包svga到线上的文件，请问这个怎么解决

**Comment by lilijialiang** [comment]
```
rules: [
  {
    test: /\.(svga)$/,
    use: [
      {
        loader: 'url-loader',
        options: {
          limit: 1
        }
      }
    ]
  }
]
```

**Comment by yiwuxing** [comment]
好的，谢谢
