### ISSUE TITLE
svga.ie.min.js文件bug

### ISSUE THREAD

**Issue by xdm123** [yyued/SVGAPlayer-Web#42]
createSWFObject方法中，成功创建后没有回调，增加回调方法后，ie9以下浏览器运行时提示错误：SCRIPT438: 对象不支持“SVGAParser_Instance_load”属性或方法

**Comment by PonyCui** [comment]
你把 swf 文件放置到工程目录下没有？

**Comment by xdm123** [comment]
> swf 文件放置到工程目录下没有？

放置了，和html文件同级

**Comment by xdm123** [comment]
> 你把 swf 文件放置到工程目录下没有？

**Comment by PonyCui** [comment]
上传一个 zip 包上来看看

**Comment by xdm123** [comment]
> 上传一个 zip 包上来看看

请问这个需要怎么解决

**Comment by PonyCui** [comment]
你需要确认 Flash 可以在浏览器中正常运行

**Comment by xdm123** [comment]
> 你需要确认 Flash 可以在浏览器中正常运行

好的，非常感谢
