### ISSUE TITLE
setImage  中imageKeys是什么

### ISSUE THREAD

**Issue by qyjandroid** [yyued/SVGAPlayer-Web#43]
setImage  中imageKeys是什么    ，问了下动画设计师，他不清楚imageKey是什么，是代表原动画中的图片名称吗？Player.setImage(r“../abc.png”, "d1.png");不好使

**Comment by PonyCui** [comment]
.setImage(“../abc.png”, "d1.png") -> .setImage(r“../abc.png”, "d1")
