### ISSUE TITLE
使用flash版本svga问题

### ISSUE THREAD

**Issue by lixiangfei** [yyued/SVGAPlayer-Web#45]
1.使用flash版本svga库，无法播放动画，问题原因：创建object对象成功，但是并没有下载swf文件(目录下有SVGAPlayerWeb.swf)
2.修改添加object的代码，可以成功下载swf，并且执行了test.svga的下载，但是没有看到播放效果
测试浏览器：chrome,IE10

    <script src="./svga.ie.min.js"></script>
      <script> 
        var player = new SVGA.Player('#test');
        var parser = new SVGA.Parser('#test'); 
        parser.load('test.svga', function(videoItem) {
            player.setVideoItem(videoItem);
            player.startAnimation();
        });
    </script>

**Comment by PonyCui** [comment]
你的 svga 文件需要是 2.0 的格式才可以使用

**Comment by lixiangfei** [comment]
谢谢，我这边试试
