### ISSUE TITLE
loops设置无效

### ISSUE THREAD

**Issue by Eivlys** [yyued/SVGAPlayer-Web#49]
html：
`<div id="demoCanvas" loops="1"></div>`

动画仍然无限循环播放

**Comment by PonyCui** [comment]
在 Player 实现上设置

**Comment by Eivlys** [comment]
> 在 Player 实例上设置

可以了 谢谢

**Comment by Eivlys** [comment]
还有个问题，player.setImage()无法替换图片，待替换图片尺寸和动画原图一致，在动画start之前执行。

**Comment by Eivlys** [comment]
> 还有个问题，player.setImage()无法替换图片，待替换图片尺寸和动画原图一致，在动画start之前执行。

Imagekey命名错误  去掉特殊符号可以了
