### ISSUE TITLE
vue 组件里边使用， 自动加载动画 没反应也没报错， <div src="../assets/img/border.svga" loops="0" clearsAfterStop="true"></div>

### ISSUE THREAD

**Issue by wuym** [yyued/SVGAPlayer-Web#59]

**Comment by wuym** [comment]
手动加载用div  标签也不行，只能用canvas

**Comment by lijialiang** [comment]
没有识别到这个 div 是一个 svga

**Comment by wuym** [comment]
> 没有识别到这个 div 是一个 svga

怎么识别到啊

**Comment by lijialiang** [comment]
1. Add Div Tag.
<div id="demoCanvas" style="styles..."></div>

2. Load Animation
var player = new SVGA.Player('#demoCanvas');

**Comment by wuym** [comment]
> 1. Add Div Tag.
>    `<div id="demoCanvas" style="styles..."></div>`
> 2. Load Animation
>    `var player = new SVGA.Player('#demoCanvas');`

这就不是自动的了，我现在出了新的问题， 一行js也不写， 也能出来  但是只能出来一个  我用了v-for  里边有多个

**Comment by lijialiang** [comment]
首先，请在因为引用库之前保证 Vue el dom 还没有渲染，其次选择适合的时机手动 new Player。
