### ISSUE TITLE
SVGAPlayer-weapp

### ISSUE THREAD

**Issue by lczc** [yyued/SVGAPlayer-Web#66]
小程序那个项目你的示例文件在我的项目中能运行，但是我自己将设计师提供的SVGA文件按照文档转换后不能显示动画。

不强求大佬继续维护那个项目，只想知道大佬的案例是怎么转换成能运行的wx.svga。

产品需求这样搞，跪求大佬了。

**Comment by lczc** [comment]
或者给我转换前的文件，我用了其他网页版的转换后也是不能运行的，只有你项目的几个例子才能运行。是转换成base64出问题了吗还是什么情况，希望大佬不吝赐教。谢谢了

**Comment by PonyCui** [comment]
微信小程序上暂时无法播放 svga 动画，因为 canvas 能力太弱。

**Comment by lczc** [comment]
确实，折腾了很久发现 设计师使用位图制作的导出来不能显示，使用2.0.0转换的也不能显示
![image](https://user-images.githubusercontent.com/30261378/63492434-1549e100-c4ec-11e9-9e66-0773903585ae.png)
xi

**Comment by whyus** [comment]
所以小程序无法使用文档居然还说支持

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Web/tree/mp
