### ISSUE TITLE
web端无法自动播放svga

### ISSUE THREAD

**Issue by 34678** [yyued/SVGAPlayer-Web#68]
![image](https://user-images.githubusercontent.com/23259141/63647582-14b48300-c756-11e9-8def-e13af42ac6f9.png)

代码如上，浏览器打开的时候无自动播放svga
环境：mac  chrome

**Comment by PonyCui** [comment]
把 script 的引入放到最下方

**Comment by 34678** [comment]
> 把 script 的引入放到最下方

可以了 感谢~

**Comment by 34678** [comment]
> > 把 script 的引入放到最下方
> 
> 可以了 感谢~

再请问一下 如果是动态插入的svga是否就不能自动播放呢， 你们的这个svga播放插件是不是 在解析的时刻自动播放当前页面已有的所有svga~

**Comment by PonyCui** [comment]
有一个 autoload 方法的，建议你还是使用代码方式处理比较好。
