### ISSUE TITLE
chrome 31 cannot run svga with svga.createjs.min.js

### ISSUE THREAD

**Issue by ddcouples** [yyued/SVGAPlayer-Web#70]
in chrome 31, svga donot work, it happen error with 
```
unknown compression method
l.load_viaProto
o.onloadend
```
so which version do it can suppot?

**Comment by PonyCui** [comment]
Chrome 31 released at the year of 2013, the best way to prevent these issue a notice user upgrade his browser.

**Comment by PonyCui** [comment]
Not gonna to fix it.

**Comment by ddcouples** [comment]
> Not gonna to fix it.

so What is the minimum supported version in Chrome?

**Comment by ddcouples** [comment]
so What is the minimum supported version in Chrome?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PonyCui"<notifications@github.com&gt;; 
发送时间: 2019年9月19日(星期四) 晚上7:33
收件人: "yyued/SVGAPlayer-Web"<SVGAPlayer-Web@noreply.github.com&gt;; 
抄送: "尘"<501894188@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yyued/SVGAPlayer-Web] chrome 31 cannot run svga with svga.createjs.min.js (#70)




Closed #70.

**Comment by PonyCui** [comment]
>= 33
< 33 lack of some libraries, such as Promise.
