### ISSUE TITLE
跟例子一模一样调用load方法但是提示svga.js?74d2:1 Uncaught incorrect header check

### ISSUE THREAD

**Issue by XdyGoGo** [yyued/SVGAPlayer-Web#73]
跟例子一模一样调用load方法但是提示svga.js?74d2:1 Uncaught incorrect header check

**Comment by lijialiang** [comment]
请把 SVGA 文件作为静态资源引入

**Comment by EuniceShaw** [comment]
SVGA文件是静态资源引入了，但是还是报这个错误。请问还有什么其他的原因？
