### ISSUE TITLE
页面加入howler仍未能播放音频

### ISSUE THREAD

**Issue by NicoNicoNicoNico** [yyued/SVGAPlayer-Web#79]
引入howler依然未播放svga中的音频
期望文档加入更详细说明
chrome75

**Comment by PonyCui** [comment]
你可以到 codepen 提供一个 demo 页面说明问题

**Comment by weixiaoting** [comment]
解决了吗？？因为有的浏览器不支持自动播放，点击下浏览器页面就可以播的了。

**Comment by PonyCui** [comment]
@weixiaoting 这是浏览器本身的限制

**Comment by weixiaoting** [comment]
嗯是的，随便点击某处，下次就会自动播放的~~~没办法
